#!/usr/bin/env bash

# Generate a temple for C project
# base_dir
#   src/
#       main.c
#   include/
#   Makefile
#   build/
#   _clang-format

set -e

BASE=$1

# I wanna break if the dir exists to avoid overriding existing files
mkdir $BASE
mkdir $BASE/{build,include,src}
touch $BASE/src/main.c
touch $BASE/Makefile

printf "#include <stdio.h>

int main(){
    puts(\"Hello from Bootstrap!\");
    return 0;
}" > $BASE/src/main.c

printf "CC      := gcc
CFLAGS  := -Wall -Wextra -g -Iinclude
SRCDIR  := src
INCDIR  := include
OBJDIR  := build
TARGET  := $BASE

SOURCES := \$(wildcard \$(SRCDIR)/*.c)
OBJECTS := \$(patsubst \$(SRCDIR)/%%.c,\$(OBJDIR)/%%.o,\$(SOURCES))
DEPFILES := \$(OBJECTS:.o=.d)

\$(TARGET): \$(OBJECTS)
	\$(CC) \$(CFLAGS) -o \$@ \$^

\$(OBJDIR)/%%.o: \$(SRCDIR)/%%.c | \$(OBJDIR)
	\$(CC) \$(CFLAGS) -MT \$@ -MMD -MP -MF \$(OBJDIR)/\$*.d -c \$< -o \$@


$\(OBJDIR):
	@mkdir -p \$@

-include \$(DEPFILES)

.PHONY: all clean run

all: \$(TARGET)

clean:
	rm -rf \$(OBJDIR) \$(TARGET)

run: \$(TARGET)
	./\$(TARGET)
" > $BASE/Makefile

printf "BasedOnStyle: LLVM
IndentWidth: 4
TabWidth: 4
UseTab: Never
BreakBeforeBraces: Attach
AllowShortIfStatementsOnASingleLine: AllIfsAndElse
AllowShortLoopsOnASingleLine: true
AllowShortCaseLabelsOnASingleLine: true
ColumnLimit: 100
PointerAlignment: Left
SpacesInParentheses: false
SpaceAfterCStyleCast: true
IncludeBlocks: Regroup
AlignConsecutiveDeclarations: Consecutive
AlignConsecutiveAssignments: Consecutive
AlignTrailingComments: true
CompactNamespaces: false
IndentCaseLabels: true
" > $BASE/.clang-format
