#!/usr/bin/env bash

set -e

sudo pacman -S --needed \
base-devel \
git \
fzf \
ripgrep \
jq \
cmatrix \
tmux \
feh \
brightnessctl \
pavucontrol \
github-cli \
unzip \
gvfs \
gvfs-mtp \
gvfs-gphoto2 \
ranger \
btop \
vim \
man-pages \
man-db \
neovim \
i3status \
i3blocks \
bat \
tokei \
fastfetch \
mako \
kitty \
wl-clipboard \
sudo-rs \
zoxide \
tree \
ffmpeg \
vlc \
vlc-plugin-ffmpeg \
xdg-desktop-portal-wlr \
rofi \
newsboat \
rsync \
gammastep

echo "Setting up Yay!"

dir=$(pwd)

# Install Yay
git clone https://aur.archlinux.org/yay.git ~/yay
cd ~/yay
makepkg -si
cd $dir
yay --version

yay -S --needed \
oxygen-cursors \
librewolf-bin \
libreoffice
