#!/usr/bin/env bash

sudo pacman -S --needed \
fzf \
ripgrep \
jq \
thunar \
cmatrix \
tmux \
feh \
brightnessctl \
pavucontrol \
github-cli \
unzip \
gvfs \
gvfs-mtp \
gvfs-gphoto2 \
ranger \
btop \
vim \
man-pages \
man-db \
neovim \
i3status \
i3blocks \
bat \
tokei \
fastfetch \
helix \
mako \
kitty \
wl-clipboard \
sudo-rs \
zoxide \
tree \
ffmpeg
